# Generated by Django 4.1.7 on 2023-02-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('des', models.TextField()),
                ('year', models.DateField()),
                ('image', models.ImageField(upload_to='img')),
            ],
        ),
    ]
